#!/usr/bin/env bash
set -euo pipefail
umask 077
[[ ${GITHUB_ACTIONS:-} == true && ${RUNNER_OS:-} == Linux ]]
readonly qa="$(cd -- "$(dirname -- "$0")" && pwd)"
readonly app="$GITHUB_WORKSPACE/app"
export QA_RUNTIME="$RUNNER_TEMP/market-xmr-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT"
export QA_APP="$app" QA_REPORT="$qa/evidence/report.json"
export COMPOSE_PROJECT_NAME="marketxmr${GITHUB_RUN_ID}a${GITHUB_RUN_ATTEMPT}"
mkdir -p "$qa/evidence"
printf '{"result":"not_started","stage":"preflight"}\n' > "$QA_REPORT"
[[ $(git -C "$app" rev-parse HEAD) == 8d22844f8c5f41caea40b5f857220db742109ef3 ]]
node --test "$qa/health.test.mjs" "$qa/registration-diagnostics.test.mjs"
[[ $(df --output=avail -B1 "$RUNNER_TEMP" | tail -1) -ge 15000000000 ]]
[[ ! -e "$QA_RUNTIME" ]]
existing_containers=$(docker ps -aq --filter "label=com.docker.compose.project=$COMPOSE_PROJECT_NAME")
existing_volumes=$(docker volume ls -q --filter "label=com.docker.compose.project=$COMPOSE_PROJECT_NAME")
[[ -z "$existing_containers" && -z "$existing_volumes" ]]
! ss -H -lnt | awk '{print $4}' | grep -Eq ':(4388[1-9]|43890|43891|49393)$'
cleanup() {
  local outcome=$?
  local cleaned=true
  set +e
  trap - EXIT TERM INT
  if [[ -f "$QA_RUNTIME/market.pid" ]]; then
    local market_pid
    local -a process_args=()
    market_pid=$(cat "$QA_RUNTIME/market.pid")
    if [[ "$market_pid" =~ ^[0-9]+$ && -d "/proc/$market_pid" ]]; then
      mapfile -d '' -t process_args < "/proc/$market_pid/cmdline"
      if [[ $(readlink "/proc/$market_pid/cwd") == "$app" && ${#process_args[@]} == 2 && ${process_args[1]} == server/index.mjs && $(readlink -f "/proc/$market_pid/exe") == $(readlink -f "$(command -v node)") ]]; then
        kill -TERM "$market_pid" 2>/dev/null
        for _ in {1..10}; do [[ ! -d "/proc/$market_pid" ]] && break; sleep 1; done
        if [[ -d "/proc/$market_pid" && $(readlink "/proc/$market_pid/cwd") == "$app" ]]; then kill -KILL "$market_pid" 2>/dev/null; sleep 1; fi
        if [[ -d "/proc/$market_pid" ]]; then outcome=1; cleaned=false; fi
      else
        outcome=1; cleaned=false
      fi
    elif [[ ! "$market_pid" =~ ^[0-9]+$ ]]; then
      outcome=1; cleaned=false
    fi
  fi
  if [[ -f "$QA_RUNTIME/compose.json" ]]; then
    docker compose -f "$QA_RUNTIME/compose.json" down --volumes --remove-orphans > "$QA_RUNTIME/cleanup.log" 2>&1 || { outcome=1; cleaned=false; }
    local remaining
    if ! remaining=$(docker ps -aq --filter "label=com.docker.compose.project=$COMPOSE_PROJECT_NAME"); then outcome=1; cleaned=false;
    elif [[ -n "$remaining" ]]; then outcome=1; cleaned=false; fi
    if ! remaining=$(docker volume ls -q --filter "label=com.docker.compose.project=$COMPOSE_PROJECT_NAME"); then outcome=1; cleaned=false;
    elif [[ -n "$remaining" ]]; then outcome=1; cleaned=false; fi
  fi
  if ss -H -lnt | awk '{print $4}' | grep -Eq ':(4388[1-9]|43890|43891|49393)$'; then outcome=1; cleaned=false; fi
  if ! QA_EXIT="$outcome" QA_CLEANED=false python3 "$qa/sanitize.py"; then
    outcome=1
    printf '{"result":"report_failed","cleanupCompleted":false}\n' > "$QA_REPORT"
  fi
  # The entire runtime is generated by prepare.py under this exact runner-owned prefix.
  if [[ "$QA_RUNTIME" == "$RUNNER_TEMP/market-xmr-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT" && -d "$QA_RUNTIME" ]]; then
    if ! sudo rm -rf -- "$QA_RUNTIME"; then
      outcome=1; cleaned=false
      printf '{"result":"cleanup_failed","cleanupCompleted":false}\n' > "$QA_REPORT"
    fi
  fi
  if [[ -e "$QA_RUNTIME" ]]; then outcome=1; cleaned=false; fi
  if ! QA_EXIT="$outcome" QA_CLEANED="$cleaned" python3 - <<'PY'
import json, os
from pathlib import Path
p = Path(os.environ['QA_REPORT'])
record = json.loads(p.read_text())
record['processExit'] = int(os.environ['QA_EXIT'])
record['cleanupCompleted'] = os.environ['QA_CLEANED'] == 'true'
if record['result'] == 'passed' and record['processExit'] != 0:
    record['result'] = 'cleanup_failed'
p.write_text(json.dumps(record, indent=2))
PY
  then outcome=1; printf '{"result":"report_failed","cleanupCompleted":false}\n' > "$QA_REPORT"; fi
  exit "$outcome"
}
trap cleanup EXIT
trap 'exit 124' TERM INT
checkpoint() {
  QA_STAGE="$1" python3 - <<'PY'
import json, os
from pathlib import Path
p = Path(os.environ['QA_REPORT'])
record = json.loads(p.read_text())
record['stage'] = os.environ['QA_STAGE']
p.write_text(json.dumps(record, indent=2))
PY
}
checkpoint prepare
python3 "$qa/prepare.py"
cp "$QA_RUNTIME/pins.json" "$qa/evidence/pins.json"
docker compose -f "$QA_RUNTIME/compose.json" config --quiet
checkpoint image_pull
timeout 15m docker compose -f "$QA_RUNTIME/compose.json" pull > "$QA_RUNTIME/pull.log" 2>&1
checkpoint harness_install
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm ci --prefix "$qa" --ignore-scripts --no-audit --no-fund > "$QA_RUNTIME/npm.log" 2>&1
checkpoint app_install
timeout 8m "$qa/node_modules/.bin/pnpm" --dir "$app" install --frozen-lockfile > "$QA_RUNTIME/app-install.log" 2>&1
checkpoint app_build
timeout 4m "$qa/node_modules/.bin/pnpm" --dir "$app" build > "$QA_RUNTIME/app-build.log" 2>&1
checkpoint service_start
docker compose -f "$QA_RUNTIME/compose.json" up -d > "$QA_RUNTIME/start.log" 2>&1
timeout --signal=TERM --kill-after=20s 25m node "$qa/verify.mjs" > "$QA_RUNTIME/verify.log" 2>&1
