import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..'),destination=path.resolve(process.argv[2]||path.join(root,'dist-release'));
const repo='agammann/Market',sha=process.env.GITHUB_SHA;
assert.equal(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.GITHUB_REPOSITORY,repo);
assert.equal(process.env.GITHUB_EVENT_NAME,'push');assert.equal(process.env.GITHUB_REF,'refs/heads/main');
assert.match(sha||'',/^[a-f0-9]{40}$/);
execFileSync('python',['scripts/check-release.py',destination,'--source',root],{cwd:root,stdio:'inherit'});
const manifest=JSON.parse(fs.readFileSync(path.join(destination,'release.json')));
assert.equal(manifest.sourceCommit,sha);const tag='v'+manifest.version;
const gh=(args)=>execFileSync('gh',args,{encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:60000});
const api=(route)=>JSON.parse(gh(['api','repos/'+repo+'/'+route]));
assert.equal(api('git/ref/heads/main').object.sha,sha,'Main advanced before publication');
const releases=api('releases');assert.ok(!releases.some(r=>r.tag_name===tag),'Release already exists; never overwrite versioned assets');
const tags=api('git/matching-refs/tags/'+tag);assert.ok(!tags.some(t=>t.ref==='refs/tags/'+tag),'Version tag already exists; investigate before publishing');
const files=fs.readdirSync(destination).sort().map(name=>path.join(destination,name));
const notes='Market '+manifest.version+' is a self-hosted reference marketplace for physical goods and digital downloads.\n\nThe source ZIP includes the application, MIT license, installation, developer and recovery instructions. It requires Docker Linux for the optional Tor deployment, or Node 24.19.0 and pnpm 11.25.0 for local development. Each seller supplies a separate supported BTCPay connection. No payment service or hosted marketplace is included.\n\nVerify the source ZIP with SHA256SUMS before extracting it. RELEASE.json records the exact source commit, tree and file hashes. Tests use isolated fixtures; actual chain verification is limited to disposable Bitcoin regtest and Monero fakechain. See docs/VERIFICATION.md for observed results and limits.';
assert.ok(process.env.RUNNER_TEMP&&path.isAbsolute(process.env.RUNNER_TEMP));
const notesFile=path.join(process.env.RUNNER_TEMP,'market-release-notes-'+sha+'.md');assert.ok(!fs.existsSync(notesFile));fs.writeFileSync(notesFile,notes);
assert.equal(api('git/ref/heads/main').object.sha,sha);
gh(['api','repos/'+repo+'/git/refs','--method','POST','--field','ref=refs/tags/'+tag,'--field','sha='+sha]);
assert.equal(api('git/ref/tags/'+tag).object.sha,sha);
gh(['release','create',tag,...files,'--repo',repo,'--target',sha,'--verify-tag','--title','Market '+manifest.version,'--notes-file',notesFile,'--draft']);
const matching=api('releases?per_page=100').filter(r=>r.tag_name===tag);assert.equal(matching.length,1,'Expected exactly one created draft');
const releaseId=matching[0].id;assert.ok(Number.isSafeInteger(releaseId)&&releaseId>0);
const release=api('releases/'+releaseId);assert.equal(release.id,releaseId);assert.equal(release.tag_name,tag);assert.equal(release.target_commitish,sha);assert.equal(release.draft,true);assert.equal(release.prerelease,false);
assert.deepEqual(release.assets.map(a=>a.name).sort(),fs.readdirSync(destination).sort());
for(const asset of release.assets){const data=fs.readFileSync(path.join(destination,asset.name));assert.equal(asset.size,data.length);assert.equal(asset.digest,'sha256:'+createHash('sha256').update(data).digest('hex'));}
assert.equal(api('git/ref/tags/'+tag).object.sha,sha);
assert.equal(api('git/ref/heads/main').object.sha,sha,'Main advanced while draft was prepared');
gh(['api','repos/'+repo+'/releases/'+releaseId,'--method','PATCH','--field','draft=false']);
const published=api('releases/'+releaseId);assert.equal(published.id,releaseId);assert.equal(published.tag_name,tag);assert.equal(published.target_commitish,sha);assert.equal(published.draft,false);
console.log(JSON.stringify({released:tag,sourceCommit:sha,sourceTree:manifest.sourceTree,assets:release.assets.map(a=>({name:a.name,size:a.size,digest:a.digest}))}));
